name: Contratos IDs ANP

on:
  schedule:
    - cron: '0 6 * * 1-5'  # Segunda a sexta às 6h UTC (3h BRT)
  workflow_dispatch:

permissions:
  actions: none
  contents: none

jobs:
  contratos_ids:
    runs-on: ubuntu-latest
    timeout-minutes: 45

    permissions:
      actions: read
      contents: write
      id-token: write

    steps:
    - name: Checkout código
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.PAT_TOKEN }}

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'

    - name: Install dependencies
      run: pip install requests beautifulsoup4

    - name: Run coleta de IDs
      run: python src/IDcontratos.py

    - name: Commit e push dos dados
      run: |
        git config --local user.email "sicap-sga@outlook.com"
        git config --local user.name "GitHub SICAP ANP Automation"
        git add data/IDcontratos.json
        git commit -m "📦 Atualização de IDs: $(date +'%Y-%m-%d %H:%M')" || echo "Sem alterações para commit"
        git push
